// Protocol fixtures adapted from upstream, revision 86bcb54cff24d4a9c96b4f14066f0098f12e87a6.
// See Resources/ThirdPartyLicenses/AIQuota-LICENSE.txt.
import Foundation
import ZislaCore

enum AIQuotaFixtures {
    static let now = Date(timeIntervalSince1970: 1_700_000_000)
    static let reference: [String: Data] = [
        "antigravity-quota": Data(#"{"response":{"groups":[{"displayName":"Gemini Models","description":"Models within this group: Gemini Flash, Gemini Pro","buckets":[{"bucketId":"gemini-weekly","displayName":"Weekly Limit Remaining","description":"You have used some of your weekly limit, it will fully refresh in 4 days, 19 hours.","window":"weekly","remainingFraction":0.9949068,"resetTime":"2026-09-11T06:11:46Z"},{"bucketId":"gemini-5h","displayName":"Five Hour Limit Remaining","window":"5h","remainingFraction":1,"resetTime":"2026-09-06T15:20:25Z"}]},{"displayName":"Claude and GPT models","description":"Models within this group: Claude Opus, Claude Sonnet, GPT-OSS","buckets":[{"bucketId":"3p-weekly","displayName":"Weekly Limit Remaining","window":"weekly","remainingFraction":1,"resetTime":"2026-09-13T10:20:25Z"},{"bucketId":"3p-5h","displayName":"Five Hour Limit Remaining","window":"5h","remainingFraction":1,"resetTime":"2026-09-06T15:20:25Z"}]}],"description":"Within each group, models share a weekly limit and a 5-hour limit."}}"#.utf8),
        "kiro-pro-plus-usage": Data(#"{"success":true,"message":"Plan: KIRO PRO+ | 2 usage breakdowns","data":{"planName":"KIRO PRO+","billingCycleReset":"2099-10-01","overagesEnabled":false,"isEnterprise":true,"usageBreakdowns":[{"resourceType":"CREDIT","displayName":"Credits","used":123.45,"limit":2000,"percentage":6,"currentOverages":0,"overageRate":0.04,"overageCharges":0,"currency":"USD","hasLimit":true},{"resourceType":"BONUS_CREDIT","displayName":"Bonus credits","used":25,"limit":100,"percentage":25,"hasLimit":true}],"bonusCredits":[],"addOnCredits":[],"overageCapable":true}}"#.utf8),
        "glm-coding-plan-quota": Data(#"{"code":200,"msg":"操作成功","data":{"limits":[{"type":"CREDIT_LIMIT","unit":3,"number":5,"usage":2000,"currentValue":0,"remaining":2000,"percentage":0},{"type":"CREDIT_LIMIT","unit":6,"number":1,"usage":10000,"currentValue":0,"remaining":10000,"percentage":0,"nextResetTime":1789373585999}],"level":"lite"},"success":true}"#.utf8),
        "command-code-credits": Data(#"{"success":true,"credits":{"planId":"individual-pro","monthlyCredits":12.5,"purchasedCredits":4,"freeCredits":0.5},"windowLimits":{"limited":true,"fiveHour":{"used":1.25,"cap":5,"resetAt":1788780000000},"weekly":{"used":21,"cap":20,"resetAt":1789200000000}}}"#.utf8),
        "command-code-credits-no-plan": Data(#"{"success":true,"credits":{"monthlyCredits":12.5,"purchasedCredits":4,"freeCredits":0.5},"windowLimits":{"limited":true,"fiveHour":{"used":1.25,"cap":5,"resetAt":1788780000000},"weekly":{"used":21,"cap":20,"resetAt":1789200000000}}}"#.utf8),
        "command-code-whoami": Data(#"{"success":true,"user":{"userId":"usr_7f3a","userName":"example"},"org":{"id":"org_2b91","login":"example-org"},"orgLimits":[{"scope":"org","spent":18.5,"limit":50,"exceeded":false,"resetInterval":"monthly","resetAt":"2026-10-01T00:00:00Z"},{"scope":"model","model":"anthropic/claude-opus-5","modelLabel":"Claude Opus 5","spent":9,"limit":10,"exceeded":false,"resetInterval":"daily","resetAt":"2026-09-10T00:00:00Z"},{"scope":"model","model":"moonshotai/Kimi-K3","modelLabel":"Kimi K3","spent":2,"limit":4,"exceeded":true,"resetInterval":"weekly","resetAt":"2026-09-14T00:00:00Z"},{"scope":"org","spent":3,"resetInterval":"total"}]}"#.utf8),
        "command-code-unlimited": Data(#"{"success":true,"credits":{"planId":"individual_go","monthlyCredits":0,"purchasedCredits":6,"freeCredits":0},"windowLimits":{"limited":false,"fiveHour":{"used":4,"cap":5,"resetAt":1788780000000},"weekly":null}}"#.utf8),
        "deepseek-balance": Data(#"{"is_available":true,"balance_infos":[{"currency":"CNY","total_balance":"42.30","granted_balance":"10.00","topped_up_balance":"32.30"}]}"#.utf8),
        "deepseek-spent": Data(#"{"is_available":false,"balance_infos":[{"currency":"CNY","total_balance":"0.00","granted_balance":"0.00","topped_up_balance":"0.00"}]}"#.utf8),
        "deepseek-two-currencies": Data(#"{"is_available":true,"balance_infos":[{"currency":"USD","total_balance":"0.00","granted_balance":"0.00","topped_up_balance":"0.00"},{"currency":"CNY","total_balance":"42.30","granted_balance":"10.00","topped_up_balance":"32.30"}]}"#.utf8),
        "devin-quota-usage": Data(#"{"daily_percentage":2,"daily_reset_at":"2026-09-14T00:00:00-08:00","has_quota_allocation":true,"hide_daily_quota":false,"is_quota_plan":true,"overage_balance":10,"weekly_percentage":1,"weekly_reset_at":"2026-09-20T00:00:00-08:00"}"#.utf8),
        "devin-quota-hidden": Data(#"{"plan_name":"team","daily_percentage":0,"weekly_percentage":58,"weekly_reset_at":1789891200000,"hide_daily_quota":true,"overage_balance_cents":250}"#.utf8),
        "devin-quota-no-allocation": Data(#"{"daily_percentage":0,"weekly_percentage":0,"has_quota_allocation":false,"is_quota_plan":false,"overage_balance":0}"#.utf8),
        "sub2api-quota": Data(#"{"isValid":true,"planName":"Claude 拼车","unit":"USD","quota":{"limit":50,"used":12.5,"remaining":37.5,"unit":"USD"},"rate_limits":[{"window":"5h","limit":100,"used":91,"remaining":9,"reset_at":"2026-09-22T09:00:00Z"},{"window":"7d","limit":700,"used":210,"remaining":490,"reset_at":"2026-09-27T00:00:00Z"}]}"#.utf8),
        "sub2api-wallet": Data(#"{"balance":16.33538288,"daily_usage":[{"date":"2026-09-20","requests":26,"input_tokens":327828,"output_tokens":30805,"total_tokens":1520745,"cost":3.665716,"actual_cost":0.6167072}],"isValid":true,"mode":"unrestricted","planName":"钱包余额","remaining":16.33538288,"unit":"USD","usage":{"rpm":0,"today":{"actual_cost":0.6167072,"cost":3.665716,"requests":26,"total_tokens":1520745},"total":{"actual_cost":13.564617106,"cost":64.081747,"requests":224,"total_tokens":26343577},"tpm":0}}"#.utf8),
        "sub2api-subscription": Data(#"{"isValid":true,"planName":"Codex 月付","subscription":{"daily_usage_usd":3.2,"daily_limit_usd":10,"weekly_usage_usd":21.5,"weekly_limit_usd":60,"monthly_usage_usd":74,"monthly_limit_usd":0,"expires_at":"2026-10-20T00:00:00Z"}}"#.utf8),
        "sub2api-refused": Data(#"{"isValid":false,"message":"key disabled"}"#.utf8),
        "qoder-credits": Data(#"{"userId":"redacted","quotaKey":"big_model_credits","nextResetAt":"2024-09-01T00:00:00Z","status":"active","totalQuota":{"quotaSummary":{"usedValue":125,"limitValue":500,"remainingValue":375,"usagePercentage":25,"unit":"credit"},"quotaDetail":[]}}"#.utf8),
        "qoder-credits-snake": Data(#"{"user_id":"redacted","quota_key":"big_model_credits","next_reset_at":1725148800000,"status":"active","total_quota":{"quota_summary":{"used_value":125,"limit_value":500,"remaining_value":375,"usage_percentage":25,"unit":"credit"},"quota_detail":[]},"plan_quota":{"quota_summary":{"used_value":125,"limit_value":300,"remaining_value":175,"usage_percentage":42,"unit":"credit"}},"resource_package_quota":{"quota_summary":{"used_value":0,"limit_value":200,"remaining_value":200,"usage_percentage":0,"unit":"credit"}}}"#.utf8),
        "qoder-credits-team": Data(#"{"userId":"redacted","quotaKey":"big_model_credits","status":"active","totalQuota":{"quotaSummary":{"usedValue":1500,"limitValue":1500,"remainingValue":0,"usagePercentage":100,"unit":"credit"}},"sharedQuota":{"quotaSummary":{"usedValue":200,"limitValue":1000,"remainingValue":800,"usagePercentage":20,"unit":"credit"}}}"#.utf8),
        "qoder-credits-none": Data(#"{"userId":"redacted","quotaKey":"big_model_credits","totalQuota":{"quotaSummary":{"usedValue":0,"limitValue":0,"remainingValue":0,"unit":"credit"},"quotaDetail":[]},"sharedQuota":{"quotaSummary":{"usedValue":0,"limitValue":0,"remainingValue":0,"unit":"credit"}}}"#.utf8),
        "volcengine-coding-plan": Data(#"{"ResponseMetadata":{"RequestId":"fixture"},"Result":{"Status":"Active","UpdateTimestamp":1788773400,"QuotaUsage":[{"Level":"weekly","Percent":41.5,"ResetTimestamp":1789085506},{"Level":"5h","Percent":12,"ResetTimestamp":1788780000},{"Level":"fortnightly","Percent":3,"ResetTimestamp":1789085506}]}}"#.utf8),
        "volcengine-agent-plan": Data(#"{"Result":{"AFPFiveHour":{"Quota":1000,"Used":250,"ResetTime":1788780000},"AFPWeekly":{"Quota":20000,"Used":0,"ResetTime":1789085506},"AFPMonthly":{"Quota":0,"Used":0,"ResetTime":0},"AFPDaily":{"Quota":500,"Used":100,"ResetTime":1788800000}}}"#.utf8),
        "v2ex-quota": Data(#"{"success":true,"message":"Current AI Chat 5h quota","result":{"active":true,"total_tokens":8020000,"used_tokens":2005000,"remaining_tokens":6015000,"used_percent":25,"period_start":1758528000,"period_end":1758546000,"extra_usage":{"pack_count":1,"total_tokens":12000000,"used_tokens":34897,"remaining_tokens":11965103}}}"#.utf8),
        "v2ex-inactive": Data(#"{"success":true,"message":"Current AI Chat 5h quota","result":{"active":false,"total_tokens":8020000,"used_tokens":0,"remaining_tokens":8020000,"used_percent":0,"period_start":0,"period_end":0,"extra_usage":{"pack_count":0,"total_tokens":0,"used_tokens":0,"remaining_tokens":0}}}"#.utf8),
        "xiaomi-plan-detail": Data(#"{"code":0,"message":"success","data":{"planCode":"coding-pro","currentPeriodEnd":"2026-10-01 00:00:00","expired":false}}"#.utf8),
        "xiaomi-plan-usage": Data(#"{"code":0,"message":"success","data":{"monthUsage":{"percent":37.5,"items":[{"name":"Coding Plan","used":3750000,"limit":10000000,"percent":37.5}]}}}"#.utf8),
        "xiaomi-balance": Data(#"{"code":0,"message":"success","data":{"balance":"42.75","currency":"CNY","cashBalance":"40.00","giftBalance":"2.75"}}"#.utf8),
        "xiaomi-no-plan": Data(#"{"code":0,"message":"success","data":{"monthUsage":{"percent":0,"items":[]}}}"#.utf8),
        "xiaomi-signed-out": Data(#"{"code":401,"message":"unauthorized","data":null}"#.utf8),
        "newapi-subscription": Data(#"{"object":"billing_subscription","has_payment_method":true,"soft_limit_usd":25.5,"hard_limit_usd":25.5,"system_hard_limit_usd":25.5,"access_until":0}"#.utf8),
        "newapi-usage": Data(#"{"object":"list","total_usage":1234.5}"#.utf8),
        "newapi-unlimited": Data(#"{"object":"billing_subscription","has_payment_method":true,"soft_limit_usd":100000000,"hard_limit_usd":100000000,"system_hard_limit_usd":100000000,"access_until":1790000000}"#.utf8),
        "newapi-status-cny": Data(#"{"success":true,"message":"","data":{"version":"v0.9.0","system_name":"示例中转","quota_per_unit":500000,"display_in_currency":true,"quota_display_type":"CNY","usd_exchange_rate":7.3}}"#.utf8),
        "newapi-status-usd": Data(#"{"success":true,"message":"","data":{"version":"v0.9.0","system_name":"Example Relay","quota_per_unit":500000,"display_in_currency":true,"quota_display_type":"USD","usd_exchange_rate":7.3}}"#.utf8),
        "newapi-status-legacy": Data(#"{"success":true,"message":"","data":{"version":"v0.5.4","system_name":"One API","quota_per_unit":500000,"display_in_currency":true}}"#.utf8),
        "newapi-status-tokens": Data(#"{"success":true,"message":"","data":{"version":"v0.9.0","system_name":"Token Relay","quota_per_unit":500000,"display_in_currency":false,"quota_display_type":"TOKENS"}}"#.utf8),
    ]

    static func json(_ object: Any) throws -> Data {
        try JSONSerialization.data(withJSONObject: object, options: [.sortedKeys])
    }
}
