import AppKit

public enum ClipboardHistoryPasteboard {
    public static func readContent(from pasteboard: NSPasteboard = .general) -> ClipboardHistoryContent? {
        guard Set(pasteboard.types ?? []).isDisjoint(with: ignoredTypes) else { return nil }
        if let fileURL = FileShelfPasteboard.readFileURLs(from: pasteboard).first,
           let content = try? ClipboardHistoryContent.file(at: fileURL) {
            return content
        }
        if let pngData = pasteboard.data(forType: .png), !pngData.isEmpty {
            return .image(pngData)
        }
        if let tiffData = pasteboard.data(forType: .tiff),
           let pngData = pngData(fromTIFF: tiffData) {
            return .image(pngData)
        }
        if let value = pasteboard.string(forType: .string) {
            let content = ClipboardHistoryContent.text(value)
            return content.isStorable ? content : nil
        }
        return nil
    }

    @discardableResult
    public static func write(
        _ content: ClipboardHistoryContent,
        to pasteboard: NSPasteboard = .general
    ) -> Bool {
        switch content {
        case .text(let value):
            pasteboard.clearContents()
            return pasteboard.setString(value, forType: .string)
        case .image(let data):
            pasteboard.clearContents()
            return pasteboard.setData(data, forType: .png)
        case .file(let reference):
            return writeFile(reference, to: pasteboard)
        }
    }

    /// Writes a file item back to the pasteboard: resolves the bookmark to restore
    /// the security scope before writing the file URL; falls back to the saved URL if
    /// the bookmark is stale.
    private static func writeFile(
        _ reference: ClipboardFileReference,
        to pasteboard: NSPasteboard
    ) -> Bool {
        var stale = false
        let resolved = try? URL(
            resolvingBookmarkData: reference.bookmark,
            options: [.withSecurityScope, .withoutUI],
            relativeTo: nil,
            bookmarkDataIsStale: &stale
        )
        let url = (resolved ?? reference.url).standardizedFileURL
        guard url.isFileURL, FileManager.default.fileExists(atPath: url.path) else {
            return false
        }
        let accessing = url.startAccessingSecurityScopedResource()
        defer { if accessing { url.stopAccessingSecurityScopedResource() } }
        pasteboard.clearContents()
        return pasteboard.writeObjects([url as NSURL])
    }

    private static func pngData(fromTIFF data: Data) -> Data? {
        guard let image = NSBitmapImageRep(data: data) else { return nil }
        return image.representation(using: .png, properties: [:])
    }

    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]
}
