import AppKit

public enum ClipboardHistoryPasteboard {
    public static func readContent(from pasteboard: NSPasteboard = .general) -> ClipboardHistoryContent? {
        guard Set(pasteboard.types ?? []).isDisjoint(with: ignoredTypes) else { return nil }
        if let pngData = pasteboard.data(forType: .png), !pngData.isEmpty {
            return .image(pngData)
        }
        if let tiffData = pasteboard.data(forType: .tiff),
           let pngData = pngData(fromTIFF: tiffData) {
            return .image(pngData)
        }
        if let value = pasteboard.string(forType: .string) {
            let content = ClipboardHistoryContent.text(value)
            return content.isStorable ? content : nil
        }
        return nil
    }

    @discardableResult
    public static func write(
        _ content: ClipboardHistoryContent,
        to pasteboard: NSPasteboard = .general
    ) -> Bool {
        pasteboard.clearContents()
        switch content {
        case .text(let value):
            return pasteboard.setString(value, forType: .string)
        case .image(let data):
            return pasteboard.setData(data, forType: .png)
        }
    }

    private static func pngData(fromTIFF data: Data) -> Data? {
        guard let image = NSBitmapImageRep(data: data) else { return nil }
        return image.representation(using: .png, properties: [:])
    }

    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]
}
